### ISSUE TITLE
Code release timeline?

### ISSUE THREAD

**Issue by Tetsujinfr** [Vio1etovo/MrMOT#1]
Hi
Thanks for the great project.
Do you have an approximate timeline for the code release?

**Comment by UsersNGT** [comment]
> Hi
> Thanks for the great project.
> Do you have an approximate timeline for the code release?

could you upload  the paper？  thanks very much。

**Comment by lpkoh** [comment]
I had the same question

**Comment by ashuezy** [comment]
+1 
Waiting for the code release

**Comment by lpkoh** [comment]
+2 following up on this

**Comment by gubei528** [comment]
Is 67hz really that fast?

**Comment by Vio1etovo** [comment]
Sorry for not posting in time due to some personal reasons, now a demo has been released.

**Comment by Tetsujinfr** [comment]
@Vio1etovo thanks. Closing this issue accordingly
